# -*- coding: utf-8 -*-

require_relative 'controller/authenticate.rb'
require_relative 'controller/auth_info.rb'
require_relative 'controller/brick.rb'
require_relative 'controller/charge.rb'
require_relative 'controller/contactmember.rb'
require_relative 'controller/contact.rb'
require_relative 'controller/content.rb'
require_relative 'controller/dept.rb'
require_relative 'controller/dnsname.rb'
require_relative 'controller/host.rb'
require_relative 'controller/hosts.rb'
require_relative 'controller/hwinfo.rb'
require_relative 'controller/ipaddress.rb'
require_relative 'controller/ipsegment.rb'
require_relative 'controller/machines.rb'
require_relative 'controller/osinfo.rb'
require_relative 'controller/rack.rb'
require_relative 'controller/rackunit.rb'
require_relative 'controller/search.rb'
require_relative 'controller/service.rb'
require_relative 'controller/smartsearch.rb'
